### POST new role

POST http://localhost:3010/api/roles
Content-Type: application/json
Cookie: sessionId=35757b86-15d3-43d5-87ac-1d44b4dc72f5

{
  "name": "train-manager",
  "description": "Can read and modify stranded trains",
  "permissions": [
    "read",
    "write"
  ]
}